# Generated by Django 5.0.2 on 2024-10-25 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_type',
        ),
    ]
