# Generated by Django 5.0.2 on 2024-10-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_areatype_base_price_and_more'),
        ('userauths', '0002_remove_profile_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.businesstype'),
        ),
    ]
