# Generated by Django 5.1.2 on 2024-10-15 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=20)),
                ('contact_cell', models.CharField(max_length=20)),
                ('contact_work_number', models.CharField(max_length=20)),
                ('industry', models.CharField(choices=[('restaurants', 'Restaurants'), ('hospitals', 'Hospitals'), ('pizza_restaurants', 'Pizza Restaurants'), ('fast_food', 'Fast Food Restaurants'), ('hotels', 'Hotels'), ('commissary_kitchens', 'Commissary Kitchens'), ('schools', 'Schools'), ('churches', 'Churches'), ('office_buildings', 'Office Buildings'), ('food_processing', 'Food Processing or Prepare Food (Big Industries)'), ('industrial_kitchens', 'Business with Industrial Kitchens'), ('other', 'Other')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KitchenEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_equipments', to='api.business')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('include_area', models.BooleanField(default=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_areas', to='api.business')),
            ],
        ),
    ]
