# Generated by Django 5.1.2 on 2024-10-17 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipment_service_remove_business_contact_cell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('square_feet', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kitchenequipment',
            name='business',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='business',
        ),
        migrations.RemoveField(
            model_name='kitchenequipment',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='size_options',
        ),
        migrations.AddField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='area',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.invoice'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.invoice'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='ServiceArea',
        ),
        migrations.DeleteModel(
            name='KitchenEquipment',
        ),
    ]
