# Generated by Django 5.1.2 on 2024-10-18 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_area_invoice_remove_business_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('Bathroom', 'Bathroom'), ('Lobby', 'Lobby'), ('Dining Room', 'Dining Room'), ('Behind the Bar', 'Behind the Bar'), ("Manager's Office", "Manager's Office"), ('Break Room', 'Break Room'), ('Patio / Terrace Area', 'Patio / Terrace Area')], max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='api.invoice'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(choices=[('Hot Plate Range', 'Hot Plate Range'), ('Ovens', 'Ovens'), ('Convection Oven', 'Convection Oven'), ('Combi Steamer', 'Combi Steamer'), ('Cooking Kettle', 'Cooking Kettle'), ('Grills', 'Grills'), ('Griddle', 'Griddle'), ('Fryers', 'Fryers'), ('Salamander', 'Salamander')], max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business_type',
            field=models.CharField(choices=[('Restaurants', 'Restaurants'), ('Hospitals', 'Hospitals'), ('Pizza Restaurants', 'Pizza Restaurants'), ('Fast Food Restaurants', 'Fast Food Restaurants'), ('Hotels', 'Hotels'), ('Commissary Kitchens', 'Commissary Kitchens'), ('Schools', 'Schools'), ('Churches', 'Churches'), ('Office Buildings', 'Office Buildings'), ('Food Processing or Prepare Food (Big Industries)', 'Food Processing or Prepare Food'), ('Business with Industrial Kitchens', 'Business with Industrial Kitchens')], max_length=100),
        ),
    ]
