# Generated by Django 5.1.2 on 2024-10-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_areatype_businesstype_equipmenttype_alter_area_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='additional_pricing_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmenttype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='AdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='api.invoice')),
            ],
        ),
    ]
