# Generated by Django 5.0.2 on 2024-10-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_areatype_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
