# Generated by Django 5.0.2 on 2024-10-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_equipment_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
