# Generated by Django 5.0.2 on 2024-10-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_areatype_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areatype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
